services:
  gorss-db:
    image: postgres
    container_name: gorss-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gorss}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gorss}
      POSTGRES_DB: ${POSTGRES_DB:-gorss}
